# Generated by Django 2.2.10 on 2020-04-02 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_auto_20200316_1730"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="login_method",
            field=models.CharField(
                choices=[("email", "Email"), ("github", "Github"), ("kakao", "Kakao")],
                default="email",
                max_length=50,
            ),
        ),
    ]
